version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

