spring:
  datasource:
    url: jdbc:mysql://localhost:3316/blog
    username: blog-api-user
    password: minjoon
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    schemas: blog
    enabled: false
    baseline-on-migrate: false
    baseline-version: 0
    encoding: UTF-8
    locations: [ "classpath:db/migration" ]